import './globals.css'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className='bg-neu-yellow bg-no-repeat'>
        {children}
      </body>
    </html>
  )
}
